apiVersion: "datadoghq.com/v2alpha1"
kind: "DatadogAgent"
metadata:
  name: "datadog"
  namespace: datadog
spec:
  global:
    kubelet:
      tlsVerify: false
    clusterName: "datadog-poc-k8s-cluster"
    registry: "gcr.io/datadoghq"
    site: "us3.datadoghq.com"
    tags:
      - "installationtype:poc"
      - "maintainer:suraj"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  override:
    clusterAgent:
      image:
        tag: "7.64.1"
  features:
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            namespaceSelector:
              matchNames:
                - "production"
            ddTraceVersions:
              js: "5"
    logCollection:
      enabled: true
      containerCollectAll: true
    usm:
      enabled: true
    npm:
      enabled: true
    orchestratorExplorer:
      enabled: true