name: Deploy Datadog Agent

on: 
  workflow_dispatch: 
    inputs:
      dd-action:
        description: Install or Un-install DataDog Agent
        default: 'Install'
        required: true
        type: choice
        options:
          - Install
          - Un-Install
      environments:
        description: Select the environment to deploy the changes
        default: 'US-DEV'
        required: true
        type: choice
        options:
          - US-DEV
          - US-QA

jobs:
  dd-agent:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Kubeconfig
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.DD_POC_CLUSTER}}

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: latest

    - name: Fetch K8s Cluster Details
      run: |
        kubectl version
        echo --------------------------------------------
        kubectl get nodes
        echo --------------------------------------------
        helm version

    - name: Create Required Namespaces
      run: |
        kubectl create namespace datadog || true

    - name: Create Datadog API Key Secret
      run: |
        kubectl get secret datadog-secret --namespace datadog >/dev/null 2>&1 || \
        kubectl create secret generic datadog-secret \
          --namespace datadog \
          --from-literal=api-key="${{ secrets.DD_API_KEY }}"

    - name: Install Datadog Operator
      id: install-dd-operator
      if: inputs.dd-action == 'Install'
      run: |
        helm repo add datadog https://helm.datadoghq.com

        helm upgrade --install datadog-operator datadog/datadog-operator --namespace datadog

    - name: Deploy Datadog Agent Configuration
      if: inputs.dd-action == 'Install'
      run: |
        kubectl apply -f dd-agent/datadog-agent.yaml
